"""
Workflow names used across the application.
"""

# Prompt Improver Workflows
IMAGE_GENERAL_PROMPT_IMPROVER = "IMAGE_GENERAL_PROMPT_IMPROVER"
IMAGE_STICKER_PROMPT_IMPROVER = "IMAGE_STICKER_PROMPT_IMPROVER"
IMAGE_PRODUCT_PROMPT_IMPROVER = "IMAGE_PRODUCT_PROMPT_IMPROVER"

TIME_PASS_WORKFLOW = "timepass"
WHATSAPP_WORKFLOW = "whatsapp"


WORKFLOW_MAP = {
    TIME_PASS_WORKFLOW: "timepass",
    WHATSAPP_WORKFLOW: "whatsapp",
}
